name: scostudent
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  shared_preferences: ^2.0.13
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.17
  font_awesome_flutter: ^9.2.0
  bubble_tab_indicator: ^0.1.6
  fl_chart: ^0.41.0
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.3.0
  flutter_typeahead: ^3.2.4
  simple_animations: ^4.0.1
  #provider: ^6.0.2
  flutter_local_notifications: ^9.2.0
  video_player: ^2.2.18
  flutter_html: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  intl: ^0.17.0
  riverpod: ^1.0.3
  flutter_svg: ^0.22.0
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^2.3.1
  like_button: ^2.0.4
  share: ^2.0.4
  another_flushbar: ^1.10.24
  image_picker: ^0.8.4+8
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  open_file: ^3.2.1
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  firebase_crashlytics: ^2.4.5
  bloc:
  flutter_bloc: ^7.2.0
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.4
  dropdown_search: ^2.0.1


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icon/logo.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adapptive_icon_foreground: "assets/app_icon/logo.jpeg"

flutter:
  fonts:
    - family: AristotelicaProTx-Dmbld
      fonts:
        - asset: fonts/AristotelicaProTx-Dmbld.otf
    - family: SF-Pro-Text-Medium
      fonts:
        - asset: fonts/SF-Pro-Text-Medium.otf
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: Tajawal-Bold
      fonts:
        - asset: fonts/Tajawal-Bold.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: fonts/Tajawal-Medium.ttf
    - family: Geeza-Pro-Regular
      fonts:
        - asset: fonts/Geeza-Pro-Regular.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: fonts/Tajawal-Regular.ttf   
          
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - i18n/ar.json
   - i18n/en.json
   - assets/images/svg/
